### ISSUE TITLE
Installer fails

### ISSUE THREAD

**Issue by phillijw** [lukevenediger/statsd.net#38]
I'm having trouble installing this server on one of our Windows Server 2008 R2 (64bit) servers. The server appears to only have .Net 4.0 which I'm assuming is the problem. Is there a way to get this app to work on .Net 4.0 instead of 4.5?

> Running a transacted installation.
> 
> Beginning the Install phase of the installation.
> See the contents of the log file for the E:\statsd.net-v1.5.0.0\statsdnet.exe assembly's progress.
> The file is located at E:\statsd.net-v1.5.0.0\statsdnet.InstallLog.
> 
> An exception occurred during the Install phase.
> System.InvalidOperationException: Unable to get installer types in the E:\statsd.net-v1.5.0.0\statsdnet.exe assembly.
> The inner exception System.Reflection.ReflectionTypeLoadException was thrown with the following error message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information..
> 
> The Rollback phase of the installation is beginning.
> See the contents of the log file for the E:\statsd.net-v1.5.0.0\statsdnet.exe assembly's progress.
> The file is located at E:\statsd.net-v1.5.0.0\statsdnet.InstallLog.
> An exception occurred during the Rollback phase of the System.Configuration.Install.AssemblyInstaller installer.
> System.InvalidOperationException: Unable to get installer types in the E:\statsd.net-v1.5.0.0\statsdnet.exe assembly.
> The inner exception System.Reflection.ReflectionTypeLoadException was thrown with the following error message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information..
> An exception occurred during the Rollback phase of the installation. This exception will be ignored and the rollback will continue. However, the machine might not fully revert to its initial state after the rollback is complete.
> 
> The Rollback phase completed successfully.
> 
> The transacted install has completed.
> 
> Running a transacted installation.
> 
> Beginning the Install phase of the installation.
> See the contents of the log file for the E:\statsd.net-v1.5.0.0\statsdnet.exe assembly's progress.
> The file is located at E:\statsd.net-v1.5.0.0\statsdnet.InstallLog.
> 
> An exception occurred during the Install phase.
> System.InvalidOperationException: Unable to get installer types in the E:\statsd.net-v1.5.0.0\statsdnet.exe assembly.
> The inner exception System.Reflection.ReflectionTypeLoadException was thrown with the following error message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information..
> 
> The Rollback phase of the installation is beginning.
> See the contents of the log file for the E:\statsd.net-v1.5.0.0\statsdnet.exe assembly's progress.
> The file is located at E:\statsd.net-v1.5.0.0\statsdnet.InstallLog.
> An exception occurred during the Rollback phase of the System.Configuration.Install.AssemblyInstaller installer.
> System.InvalidOperationException: Unable to get installer types in the E:\statsd.net-v1.5.0.0\statsdnet.exe assembly.
> The inner exception System.Reflection.ReflectionTypeLoadException was thrown with the following error message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information..
> An exception occurred during the Rollback phase of the installation. This exception will be ignored and the rollback will continue. However, the machine might not fully revert to its initial state after the rollback is complete.
> 
> The Rollback phase completed successfully.
> 
> The transacted install has completed.

**Comment by lukevenediger** [comment]
Hi Joe,

Sorry, but the service needs .net 4.5 and upwards to run.

Thanks,
Luke
